#!/usr/bin/env bash


SCRIPT_INPUT='/tmp/input'
cat > $SCRIPT_INPUT <&0 # STDIN params

SERVER=$(jq -r '(.source.servers + [.source.server])[0]' < $SCRIPT_INPUT)
PORT=$(jq -r '.source.port // ""' < $SCRIPT_INPUT)
BASE_DIR=$(jq -r '.source.base_dir // ""' < $SCRIPT_INPUT)
USER=$(jq -r '.source.user // ""' < $SCRIPT_INPUT)
VERSION=$(jq -r '.version.ref // ""' < $SCRIPT_INPUT)
jq -re '.source.disable_version_path' < $SCRIPT_INPUT >/dev/null
DISABLE_VERSION_PATH=$?

## check if port is set in the configuration and
## use default SSH port number 22 otherwise
if [ -z "$PORT" ]; then
    PORT=22
fi

echo $SCRIPT_INPUT 1>&2
echo $SERVER    1>&2
echo $PORT      1>&2
echo $BASE_DIR  1>&2
echo $USER      1>&2
echo $VERSION  1>&2

mkdir -p ~/.ssh
(jq -r '.source.private_key // empty' < $SCRIPT_INPUT) > ~/.ssh/server_key
echo -e "Host $SERVER\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
chmod -R 600 ~/.ssh

eval $(ssh-agent)  1>&2  >/dev/null
SSH_ASKPASS=/opt/resource/askpass.sh DISPLAY= ssh-add ~/.ssh/server_key  1>&2  >/dev/null

REFS=''
DIR=${BASE_DIR##*/}
echo $DIR 1>&2
REFS="{ \"ref\": \"$(ssh -i ~/.ssh/server_key \"find $BASE_DIR -type f -exec stat -c "%Y" {} \; | sort -n | tail -1\")\" }"

echo "Determined refs to be: $REFS"  1>&2

OUTPUT_STRING="[ $REFS ]"
echo $OUTPUT_STRING
exit 0
