#!/usr/bin/env python

import json
import os 
import subprocess
import sys
import paramiko

DEBUG = True if os.getenv('DEBUG') == 'true' else False

if DEBUG:
    print('===\nOUT\n===')

def in_(instream):
    pr_config = json.load(instream)

    if not pr_config.get('version', None):
        pr_config['version'] = dict()

    sys_dir = sys.argv[1]
    server = pr_config["source"].get('server')
    port = pr_config["source"].get('port', 22)
    private_key = pr_config["source"].get('private_key','')
    base_dir = pr_config["source"].get('base_dir')
    sync_dirs = [ os.path.join(str(sys_dir), str(x)) for x in pr_config["source"].get('sync_dirs')]
    user = pr_config["source"].get('user')
    version = pr_config.get("version", dict())
    params = pr_config.get("params", {}).get('rsync_opts','')
    disable_version_path = True if pr_config['source'].get('disable_version_path', 'false') == 'true' else False

    stdout = {}

    if DEBUG:
        print('server', server)
        print('port', port)
        print('private_key', private_key)
        print('base_dir', base_dir)
        print('sync_dirs', sync_dirs)
        print('user', user)
        print('version', version)
        print('disable_version_path', disable_version_path)

    home_user = os.path.expanduser('~')

    server_key = os.path.join(home_user, '.ssh/server_key')
    ssh_config = os.path.join(home_user, '.ssh/config')
    ssh_folder = os.path.join(home_user, '.ssh')
    os.makedirs(ssh_folder, exist_ok=True)

    cmd = 'echo \'%s\' > %s' % (private_key.replace('\\n', '\n'), server_key)
    ps = subprocess.Popen(cmd,shell=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    output = ps.communicate()[0]

    cmd = 'echo \'Host $SERVER\n\tStrictHostKeyChecking no\n\' > %s' % (ssh_config)
    ps = subprocess.Popen(cmd,shell=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    output = ps.communicate()[0]

    os.chmod(server_key,  int('600', base=8))
    os.chmod(ssh_config,  int('600', base=8))

    k = paramiko.RSAKey.from_private_key_file(server_key)
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(hostname=server, username=user, pkey=k, port=port)

    valid_dirs = []
    for dir in sync_dirs:
        if 'No such file or directory'.lower() in dir.lower():
            valid_dirs.append(dir)

    cmd = "find " + " ".join(valid_dirs) + " -printf '%T@ %p\n' | sort -n "
    ps = subprocess.Popen(cmd,shell=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    output = ps.communicate()[0].decode('utf-8').split('\n')

    # remove any directories that were empty

    output_len = len(output)
    recent_file = output[output_len - 2]
    recent_timestamp = recent_file.split(' ')[0].split('.')[0]

    if DEBUG:
        print('Cmd:              ', cmd)
        print('Sync Dirs:        ', valid_dirs)
        print('Recent Files:     ', output_len, '\n', output)
        print('Recent File:      ', recent_file)
        print('Recent Timestamp: ', recent_timestamp)

    stdout['version'] = {}
    stdout['version']['ref'] = str(recent_timestamp)
    stdout['metadata'] = []
    stdout['metadata'].append({'name' : 'Num Files', 'value': str(output_len)})

    remote_sync_dir = os.path.join(base_dir, recent_timestamp)
    stdout['metadata'].append({'name' : 'Remote Sync Dir', 'value': remote_sync_dir})

    cmd = "mkdir -p " + remote_sync_dir
    ssh_stdin, ssh_stdout, ssh_stderr = ssh.exec_command(cmd)
    if DEBUG:
        print(ssh_stdout.read())
        print(ssh_stderr.read())

    cmd = u"rsync -avPt %s -e 'ssh -i ~/.ssh/server_key -o StrictHostKeyChecking=no -p %s' %s %s@%s:%s" % (params, port, " ".join(sync_dirs), user, server, remote_sync_dir)
    ps = subprocess.Popen(cmd,shell=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    output = ps.communicate()[0]
    if DEBUG:
        print('cmd', cmd)
        print(ssh_stdout.read())
        print(ssh_stderr.read())

    return stdout

def main():
    print(json.dumps(in_(sys.stdin)))

if __name__ == '__main__':
    main()
